###################################################   Variables   ##################################################
define: &learn_sigma True

###################################################    Config     ##################################################
name: debug_dd_unet_fsc

vae:
  enabled: True
  path: "stabilityai/sdxl-vae"
  cache: "../FSC147_384_V2/latents/debugging" # todo

diffusion:
  schedule_sampler: "uniform"
  type: "Denoise" # or Deblur
  params:
    diffusion_steps: 1000
    noise_schedule: scaled_linear
    learn_sigma: *learn_sigma
    sigma_small: False
    use_kl: False
    parametrization: "v"
    rescale_timesteps: False
    rescale_learned_sigmas: False
    timestep_respacing: ""
    lmbd_vlb: 0.001
    lmbd_xs_count: 0.0
    lmbd_cb_count: 0.0
    t_mse_weighting_scheme: "uniform"
    t_xs_count_weighting_scheme: "exp"
    t_cb_count_weighting_scheme: "exp"
    enforce_zero_terminal_snr: True

model:
  type: "UNet" # or DiT
  params:
    input_size: 32
    in_channels: 8
    model_channels: 32
    out_channels: 4
    num_res_blocks: 2
    attention_resolutions: [32, 16, 8]
    dropout: 0.0
    channel_mult: [1, 2, 4]
    conv_resample: True
    dims: 2
    y_dim: null
    context_dim: null
    use_checkpoint: True
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: True
    resblock_updown: True
    adalnzero: False
    learn_count: False
    learn_sigma: *learn_sigma
    transformer_depth: 1
    initial_ds: 0.125
    num_bboxes: 3
    bbox_dim: adaptive

conditioner:
  embedders:
    - type: "ImageConcatEmbedder"
      input_keys: ["img"]
      is_trainable: False

    - type: "BBoxAppendEmbedder"
      input_keys: ["bboxes"]
      is_trainable: False

    # - type: "RoIAlignExemplarEmbedder"
    #   input_keys: ["img", "bboxes"]
    #   is_trainable: True
    #   params:
    #     in_channels: 4
    #     roi_output_size: 7
    #     out_channels: 256
    #     remove_sequence_dim: False

    # - type: "ViTExemplarEmbedder"
    #   input_keys: ["img", "bboxes"]
    #   is_trainable: True
    #   params:
    #     input_size: 16
    #     in_channels: 4
    #     out_channels: 64
    #     vit_size: "B"
    #     freeze_backbone: False
    #     remove_sequence_dim: True

data:
  dataset:
    name: "FSC147"
    params:
      datadir: ../FSC147_384_V2/
      targetdir: densitymaps/debugging
      n_exemplars: 3
      image_size: 256
      hflip_p: 0.5
      cj_p: 0.0
      sigma: 0.5
      center_pad: True
      bbox_max_size: null
      bbox_min_size: null
      allow_resize_target: False
      target_minmax_norm: True

  dataloader:
    params:
      batch_size: 2
      overfit_single_batch: True

train:
  lr: 1.e-4
  num_epochs: 10000
  grad_clip: 1.0
  use_fp16: False
  ema_rate: 0.9999
  validation_interval: 10000
  resume_checkpoint: null
  weight_decay: 0.0
  lr_scheduler: null
  seed: 42

log:
  logdir: ../experiments/dummy/
  wandb_mode: disabled
  log_interval: 10
  save_interval: 10000