###################################################   Variables   ##################################################
define: &image_size 256
define: &learn_sigma True

###################################################    Config     ##################################################
name: debug_dd_unet_fsc
vae: "stabilityai/sdxl-vae"
# vae: null
diffusion:
  schedule_sampler: "uniform"
  type: "Denoise" # or Deblur
  params:
    diffusion_steps: 250
    noise_schedule: linear
    learn_sigma: *learn_sigma
    sigma_small: False
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: False
    timestep_respacing: ""
    lmbd_vlb: 0.001
    lmbd_count: 0.005
    pred_count_from_xstart: False
    t_count_weighting_scheme: "exp"
    k: 25.0

model:
  type: "UNet" # or DiT
  params:
    input_size: 64
    in_channels: 8
    model_channels: 32
    out_channels: 4
    num_res_blocks: 2
    attention_resolutions: [32, 16, 8]
    dropout: 0.0
    channel_mult: [1, 2, 3, 4]
    conv_resample: True
    dims: 2
    y_dim: null
    context_dim: null
    use_checkpoint: True
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: True
    resblock_updown: True
    adalnzero: False
    learn_count: False
    learn_sigma: *learn_sigma

conditioner:
  embedders:
    - type: "ImageConcatEmbedder"
      input_keys: ["img"]
      is_trainable: False

    # - type: "ViTExemplarEmbedder"
    #   input_keys: ["img", "bboxes"]
    #   is_trainable: True
    #   params:
    #     input_size: 16
    #     in_channels: 4
    #     out_channels: 64
    #     vit_size: "B"
    #     freeze_backbone: False
    #     remove_sequence_dim: True

data:
  dataset:
    name: "FSC147"
    params:
      datadir: ../FSC147_384_V2/
      targetdir: densitymaps/debugging
      n_exemplars: 3
      image_size: 512
      hflip_p: 0.5
      cj_p: 0.0
      sigma: 0.5
      center_pad: True
      bbox_max_size: 50
      bbox_min_size: 10
      allow_resize_target: False
      target_minmax_norm: True

  dataloader:
    params:
      batch_size: 2
      overfit_single_batch: True

train:
  lr: 1.e-4
  num_epochs: 10
  grad_clip: -1.0
  use_fp16: False
  ema_rate: 0.9999
  validation_interval: 5
  resume_checkpoint: null
  weight_decay: 0.0
  lr_scheduler: null
  seed: 42

log:
  logdir: ../experiments/dummy/
  wandb_mode: disabled
  log_interval: 10
  save_interval: 10000