name: exp1
seed: 42

diffusion:
  schedule_sampler: "uniform"
  type: "Denoise" # or Deblur
  params:
    diffusion_steps: 250
    noise_schedule: linear
    learn_sigma: False
    sigma_small: False
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: False
    timestep_respacing: ""

model:
  type: "UNet" # or DiT
  params:
    image_size: 128
    in_channels: 4
    model_channels: 32
    out_channels: 1
    num_res_blocks: 2
    attention_resolutions: [32, 16, 8]
    dropout: 0.0
    channel_mult: null
    conv_resample: True
    dims: 2
    y_dim: null
    context_dim: 64
    use_checkpoint: True
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: True
    resblock_updown: True

conditioner:
  type: "FSC147"
  params:
    image_size: 128
    out_channels: 64
    vit_size: "B"
    freeze_backbone: True
    remove_sequence_dim: False
    is_trainable: False

data:
  dataset:
    name: "FSC147"
    params:
      datadir: ../FSC147_384_V2/
      targetdir: densitymaps/exp1/
      n_exemplars: 3
      image_size: 128
      tile_size: 128
      hflip_p: 0.5
      cj_p: 0.0
      sigma: 0.5

  dataloader:
    params:
      batch_size: 2
      overfit_single_batch: True

train:
  lr: 1.e-4
  num_epochs: 10000
  dropout: 0.0
  grad_clip: 1.0
  use_fp16: False
  ema_rate: 0.9999
  validation_interval: 1000
  resume_checkpoint: null
  weight_decay: 0.0

log:
  logdir: ../experiments/dummy/
  wandb_mode: disabled
  log_interval: 10
  save_interval: 10000