name: exp2
seed: 42 # todo

diffusion:
  schedule_sampler: "uniform"
  type: "Deblur" # or Deblur
  params:
    diffusion_steps: 100
    blur_schedule: "log"
    min_sigma: 0.5
    max_sigma: 20.0
    image_size: 28
    loss_type: "l1"
    use_dct: False
    delta: 0.01

model:
  type: "UNet" # or DiT
  params:
    image_size: 28
    in_channels: 1
    model_channels: 32
    out_channels: 1
    num_res_blocks: 2
    attention_resolutions: [2]
    dropout: 0.0
    channel_mult: [1, 2, 2]
    conv_resample: True
    dims: 2
    num_classes: null
    use_checkpoint: True
    num_heads: -1
    num_head_channels: 64
    num_heads_upsample: -1
    use_scale_shift_norm: True
    resblock_updown: True
    transformer_depth: 1
    context_dim: 128
    disable_self_attentions: null
    num_attention_blocks: null
    disable_middle_self_attn: False
    disable_middle_transformer: False
    use_linear_in_transformer: False
    spatial_transformer_attn_type: softmax-xformers
    adm_in_channels: null

conditioner:
  type: "MNIST"
  params:
    embed_dim: 128
    is_trainable: False
    add_sequence_dim: True

data:
  dataset:
    name: "MNIST"
    params:
      datadir: ../.data/mnist

  dataloader:
    params:
      batch_size: 4
      fraction_of_data: 1.0
      overfit_single_batch: True

train:
  lr: 2.e-4
  num_epochs: 10000
  dropout: 0.0
  grad_clip: -1.0
  use_fp16: False
  ema_rate: 0.9999
  validation_interval: 200
  resume_checkpoint: null
  weight_decay: 0.0

log:
  logdir: ../experiments/dummy/
  wandb_mode: disabled
  log_interval: 10
  save_interval: 10000