name: exp2
seed: 42 # todo

diffusion:
  schedule_sampler: "uniform"
  type: "Denoise" # or Deblur
  params:
    diffusion_steps: 250
    noise_schedule: linear
    learn_sigma: True
    sigma_small: False
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: True
    timestep_respacing: ""

model:
  type: "UNet" # or DiT
  params:
    image_size: 256
    in_channels: 4
    model_channels: 192
    out_channels: 1
    num_res_blocks: 2
    attention_resolutions: [32, 16, 8]
    dropout: 0.0
    channel_mult: null
    conv_resample: True
    dims: 2
    y_dim: 768
    context_dim: null
    use_checkpoint: True
    num_heads: 1
    num_head_channels: -1
    num_heads_upsample: -1
    use_scale_shift_norm: True
    resblock_updown: True

#conditioner:
#  type: "MNIST"
#  params:
#    embed_dim: 128
#    is_trainable: False
#    add_sequence_dim: True
conditioner:
  type: "FSC147"
  params:
    image_size: 256
    out_channels: 256
    vit_size: "B"
    freeze_backbone: True
    remove_sequence_dim: True
    is_trainable: False

# data:
#   dataset:
#     name: "MNIST"
#     params:
#       datadir: ../.data/mnist

#   dataloader:
#     params:
#       batch_size: 4
#       fraction_of_data: 1.0
#       overfit_single_batch: True
data:
  dataset:
    name: "FSC147"
    params:
      datadir: /d/hpc/projects/FRI/DL/gs1121/FSC147_384_V2/
      targetdir: densitymaps/exp2/
      n_exemplars: 3
      image_size: 256
      tile_size: 256
      hflip_p: 0.5
      cj_p: 0.0
      sigma: 0.5
  dataloader:
    params:
      batch_size: 4
      overfit_single_batch: False

train:
  lr: 1.e-4
  num_epochs: 0
  dropout: 0.0
  grad_clip: 1.0
  use_fp16: True
  ema_rate: 0.9999
  validation_interval: 1
  resume_checkpoint: /d/hpc/projects/FRI/DL/gs1121/128_512_upsampler.pt
  # resume_checkpoint: null
  weight_decay: 0.0

log:
  logdir: /d/hpc/projects/FRI/DL/gs1121/logs/
  wandb_mode: online
  log_interval: 100
  save_interval: 100