name: exp3
seed: 42 # todo

# diffusion:
#   schedule_sampler: "uniform"
#   type: "Deblur" # or Deblur
#   params:
#     diffusion_steps: 150
#     blur_schedule: "log"
#     min_sigma: 0.5
#     max_sigma: 20.0
#     image_size: 28
#     loss_type: "l1"
#     use_dct: False
#     delta: 0.01

diffusion:
  schedule_sampler: "uniform"
  type: "Denoise" # or Deblur
  params:
    diffusion_steps: 250
    noise_schedule: linear
    learn_sigma: False
    sigma_small: False
    use_kl: False
    predict_xstart: False
    rescale_timesteps: False
    rescale_learned_sigmas: False
    timestep_respacing: ""

model:
  type: "DiT" # or DiT
  params:
    dit_size: "DiT-S/2"
    input_size: 64
    in_channels: 4
    out_channels: 1
    context_dim: null
    adm_in_channels: 768

conditioner:
  type: "FSC147"
  params:
    image_size: 64
    out_channels: 256
    vit_size: "B"
    freeze_backbone: True
    remove_sequence_dim: True
    is_trainable: False

data:
  dataset:
    name: "FSC147"
    params:
      datadir: ../FSC147_384_V2/
      targetdir: densitymaps/sig_0.5/size_256/
      n_exemplars: 3
      transform_kwargs:
        image_size: 64
        hflip_p: 0.5
        cj_p: 0.0

  dataloader:
    params:
      batch_size: 4
      fraction_of_data: 1.0
      overfit_single_batch: True

train:
  lr: 2.e-4
  num_epochs: 10000
  dropout: 0.0
  grad_clip: -1.0
  use_fp16: False
  ema_rate: 0.9999
  validation_interval: 200
  resume_checkpoint: null
  weight_decay: 0.0

log:
  logdir: ../experiments/dummy/
  wandb_mode: disabled
  log_interval: 10
  save_interval: 10000